# Author: Ani G.
# Sa makefile e java file-ery build ev run anelu hamar

source=Parz_tiv.java Main.java
compiler=javac
output=*.class
classfile=Main.class
exefile=Main
interpretator=java

compile: $(source)
	$(compiler) $(source)
clean: $(output)
	rm -f $(output)
run: $(classfile)
	$(interpretator) $(exefile) 10001


