
# Author: Ani G.
# Sa makefile e java file-ery build ev run anelu hamar

SOURCE=Transport.java Metro.java Ertuxayin.java Main.java
compiler=javac
output=*.class
classfile=Main.class
exefile=Main
interpretator=java

compile: $(SOURCE)
	$(compiler) $(SOURCE)
clean: $(output)
	rm -f $(output)
run: $(classfile)
	$(interpretator) $(exefile) 200


