
# Author: Ani G.
# Sa makefile e java file-ery build ev run anelu hamar

SOURCE=*.java
compiler=javac
output=*.class
classfile=Main.class
run=Main
interpretator=java

compile: $(SOURCE)
	$(compiler) $(SOURCE)
clean: $(output)
	rm -f $(output)
run: $(classfile)
	$(interpretator) $(run) 200


